name: Generate Activity Graph

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Generate Activity Graph
        run: |
          npm install -g @ashutosh00710/github-readme-activity-graph
          generate-activity-graph --username Pranshu936 --output ./images/activity-graph.svg

      - name: Commit & Push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add ./images/activity-graph.svg
          git commit -m 'Update activity graph'
          git push
